### ISSUE TITLE
Send, Sync for Commitment

### ISSUE THREAD

**Issue by ggutoski** [EspressoSystems/commit#32]
`Commitment` does not have `Send`, `Sync`. As a general-purpose library, it would be nice if it did.

Why is `Send`, `Sync` missing from `Commitment`? Because it has a type param `T` that may not be `Send`, `Sync`.

https://github.com/EspressoSystems/commit/blob/bbcb4d8ab33cf76dc92053446389af6c705179a3/src/lib.rs#L89

Of course, we use only `PhantomData<T>`, so `Commitment` *should* be both `Send` and `Sync`. I don't know the idiomatic way to recover `Send`, `Sync` for a struct with `PhantomData`.

**Comment by jbearer** [comment]
Ah, there's a trick. I believe if you replace `PhantomData<T>` with `PhantomData<fn(&T)>` you get the maximum of Send, Sync, Sized, and 'static that the rest of the type allows
